"""Create the private runtime config used by the Android build."""

import os
from pathlib import Path


web_app_url = os.environ.get("GOOGLE_SHEETS_WEB_APP_URL", "").strip()
sync_token = os.environ.get("GOOGLE_SHEETS_SYNC_TOKEN", "").strip()

if not web_app_url.startswith("https://script.google.com/macros/s/"):
    raise SystemExit("GOOGLE_SHEETS_WEB_APP_URL is missing or invalid.")

if len(sync_token) < 32:
    raise SystemExit("GOOGLE_SHEETS_SYNC_TOKEN is missing or too short.")

config = (
    "# Generated by GitHub Actions. Do not commit this file.\n"
    f"GOOGLE_SHEETS_WEB_APP_URL = {web_app_url!r}\n"
    f"GOOGLE_SHEETS_SYNC_TOKEN = {sync_token!r}\n"
)

Path("sheets_private.py").write_text(config, encoding="utf-8")
